# .goreleaser.yaml
version: 2

project_name: exevo-terra

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin # Mac
    goarch:
      - amd64
      - arm64 # Apple Silicon / Graviton

archives:
  - format: tar.gz
    # Isso vai criar arquivos tipo: exevo-terra_1.0.0_Linux_x86_64.tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # Usa zip para windows
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'